import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weights: [400, 700],
  display: "swap",
});

export const metadata = {
  title: "Mouniesh's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${spaceGrotesk.variable} antialiased font-space-grotesk transition-colors duration-300`}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <Navbar />
          <div>
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}